-- 00_create_staging_tables.sql
-- Raw staging tables for the three UN Comtrade pull tracks.
-- Every column is TEXT on purpose: this is a raw landing zone, not the
-- analysis-ready schema. Casting to proper types (int, numeric, boolean,
-- date) and cleaning belongs in 01_data_cleaning.sql, not here.
--
-- Column order below matches the CSV header order exactly — pgAdmin's
-- Import/Export Data tool loads positionally, so this order must not change
-- unless the CSV column order also changes.

DROP TABLE IF EXISTS raw_track_a_country_benchmark;
CREATE TABLE raw_track_a_country_benchmark (
    typecode                text,
    freqcode                text,
    refperiodid             text,
    refyear                 text,
    refmonth                text,
    period                  text,
    reportercode            text,
    reporteriso             text,
    reporterdesc            text,
    flowcode                text,
    flowdesc                text,
    partnercode             text,
    partneriso              text,
    partnerdesc             text,
    partner2code            text,
    partner2iso             text,
    partner2desc            text,
    classificationcode      text,
    classificationsearchcode text,
    isoriginalclassification text,
    cmdcode                 text,
    cmddesc                 text,
    aggrlevel               text,
    isleaf                  text,
    customscode             text,
    customsdesc             text,
    moscode                 text,
    motcode                 text,
    motdesc                 text,
    qtyunitcode             text,
    qtyunitabbr             text,
    qty                     text,
    isqtyestimated          text,
    altqtyunitcode          text,
    altqtyunitabbr          text,
    altqty                  text,
    isaltqtyestimated       text,
    netwgt                  text,
    isnetwgtestimated       text,
    grosswgt                text,
    isgrosswgtestimated     text,
    cifvalue                text,
    fobvalue                text,
    primaryvalue            text,
    legacyestimationflag    text,
    isreported              text,
    isaggregate             text
);

DROP TABLE IF EXISTS raw_track_b_india_sector_detail;
CREATE TABLE raw_track_b_india_sector_detail (
    typecode                text,
    freqcode                text,
    refperiodid             text,
    refyear                 text,
    refmonth                text,
    period                  text,
    reportercode            text,
    reporteriso             text,
    reporterdesc            text,
    flowcode                text,
    flowdesc                text,
    partnercode             text,
    partneriso              text,
    partnerdesc             text,
    partner2code            text,
    partner2iso             text,
    partner2desc            text,
    classificationcode      text,
    classificationsearchcode text,
    isoriginalclassification text,
    cmdcode                 text,
    cmddesc                 text,
    aggrlevel               text,
    isleaf                  text,
    customscode             text,
    customsdesc             text,
    moscode                 text,
    motcode                 text,
    motdesc                 text,
    qtyunitcode             text,
    qtyunitabbr             text,
    qty                     text,
    isqtyestimated          text,
    altqtyunitcode          text,
    altqtyunitabbr          text,
    altqty                  text,
    isaltqtyestimated       text,
    netwgt                  text,
    isnetwgtestimated       text,
    grosswgt                text,
    isgrosswgtestimated     text,
    cifvalue                text,
    fobvalue                text,
    primaryvalue            text,
    legacyestimationflag    text,
    isreported              text,
    isaggregate             text,
    sector                  text
);

DROP TABLE IF EXISTS raw_track_c_india_partner_view;
CREATE TABLE raw_track_c_india_partner_view (
    typecode                text,
    freqcode                text,
    refperiodid             text,
    refyear                 text,
    refmonth                text,
    period                  text,
    reportercode            text,
    reporteriso             text,
    reporterdesc            text,
    flowcode                text,
    flowdesc                text,
    partnercode             text,
    partneriso              text,
    partnerdesc             text,
    partner2code            text,
    partner2iso             text,
    partner2desc            text,
    classificationcode      text,
    classificationsearchcode text,
    isoriginalclassification text,
    cmdcode                 text,
    cmddesc                 text,
    aggrlevel               text,
    isleaf                  text,
    customscode             text,
    customsdesc             text,
    moscode                 text,
    motcode                 text,
    motdesc                 text,
    qtyunitcode             text,
    qtyunitabbr             text,
    qty                     text,
    isqtyestimated          text,
    altqtyunitcode          text,
    altqtyunitabbr          text,
    altqty                  text,
    isaltqtyestimated       text,
    netwgt                  text,
    isnetwgtestimated       text,
    grosswgt                text,
    isgrosswgtestimated     text,
    cifvalue                text,
    fobvalue                text,
    primaryvalue            text,
    legacyestimationflag    text,
    isreported              text,
    isaggregate             text
);
